# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: activeadmin
    ports:
      - 54321:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  message-db:    
    image: ethangarofolo/message-db
    ports:    
      - '0.0.0.0:5432:5432'
