# See README for information
version: '3.1'

services:
  message-db:
    image: ethangarofolo/message-db
    ports:
      - '0.0.0.0:5432:5432'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: activeadmin
    ports:
      - 54321:5432
